### ISSUE TITLE
Mark as unread

### ISSUE THREAD

**Issue by hollov** [zulip/zulip-desktop#1072]
Ability to mark messages as unread

**Comment by Elv1zz** [comment]
That would be a really useful feature!
Alternatively the "Starred messages" category should have a message count badge, so I can star the messages at least and see that I have to come back to them later.

**Comment by timabbott** [comment]
Thanks for the feedback!

This is a duplicate of https://github.com/zulip/zulip/issues/2676 -- I encourage you to upvote there.

That said, the "Starred messages" category does have an optional message count badge, in "display settings".  It's probably a mistake that isn't enabled by default for new users -- I'll take care of fixing that now since it's really quick.
