### ISSUE TITLE
desktop client clears organizations on restart

### ISSUE THREAD

**Issue by rmbellovin** [zulip/zulip-desktop#1079]
I am running the zulip desktop client on ubuntu 20.04, and sometimes (but not always) the client clears the organizations I've joined if I restart it, and I have to re-add each of them.  Is there a way to stop this from happening?

**Comment by timabbott** [comment]
We certainly haven't seen other reports of this; we'd love to investigate.  The organizations are stored in dotfiles in the user's home directory on Linux, though it may depend on how you installed it.  Can you stop by #desktop on chat.zulip.org for more interactive debugging?

How many times has this happened, and which package are you using?  I wonder if what's secretly happening is a bug with the auto-update process.

**Comment by rmbellovin** [comment]
I don't have a good estimate for how many times it's happened, unfortunately.  My current version is 5.6 (I followed the instructions to add it to `apt`); my organizations were cleared shortly before I opened this issue, and I think there was an update not long before.

I'm happy to chat at chat.zulip.org.  I can talk for a bit now, and I'm generally on GMT.

**Comment by andersk** [comment]
I believe this was caused by the misguided `postrm` script added in #349. I had already decided that script looked fishy and removed it for 5.6.0 (109795ca3e6b247070712f60bbc62aeaa45deb84). Unfortunately, because `dpkg` runs the `postrm` script from the _old_ version on upgrades, the 5.5.0 → 5.6.0 upgrade was still affected. But this shouldn’t happen in future upgrades.

Thanks for your help debugging this!
