### ISSUE TITLE
App unread badge not working (Mac)

### ISSUE THREAD

**Issue by chris-fh** [zulip/zulip-desktop#1083]
**Describe the bug**
The unread badge disappears after a while and Zulip does not show unread messages in Dock icon. After moving zulip to trash and reinstalling it it reappears for a day or so.

**Expected behavior**
enabling and disabling the "Show app unread badge" button in Settings -> Appearance should take effect.
Once enabled it should show unread messages in the Dock/Tray icon.

**Desktop (please complete the following information):**
 - Operating System: macOS 
 Catalina 10.15.7
 - Zulip Desktop Version:
Version: 5.6.0

**Comment by brianharvey** [comment]
+1.  Zulip 5.7.0, MacOS 10.13.4  (so Apple didn't just break it...)

**Comment by chris-fh** [comment]
Turns out I had to (re)enable  > System Preferences > Notifications for Zulip. Somehow it got disabled by an update I assume.

**Comment by brianharvey** [comment]
Wait does that make the little dot appear in the menu bar, or does it just make a big rounded rectangle appear up in the corner?

**Comment by chris-fh** [comment]
The symbol in the dock gets a red dot that has the number of unread messages enclosed. I am not talking about the menu bar and I have not encountered a big rounded rectangle.

**Comment by brianharvey** [comment]
Oh.  I generally keep the dock hidden, and most software that handles asynchronous events and has an icon in the menu bar flags events in that menu bar icon (e.g., Dropbox, Telegram, Adobe Creative Cloud).  Can I reopen this?  Or should I start a new issue report?

**Comment by chris-fh** [comment]
Now that I think about it... I do see a rounded rectangle in the upper right corner whenever I get a new message.
Up to you to reopen this, if you think your problem applies...

**Comment by johnathanz** [comment]
hm.... I'm on Mac Ventura 13.6.7, running the latest Zulip mac client.

Whenever a new message comes in, I get the notification slide in as a Banner / Alert (top right side).

But there is no unread icon in:
* Zulip Dock icon
* Zulip menu bar icon
* left sidebar icon within Zulip

Zulip notification setting
![2024-07-06 at 15 06 00](https://github.com/zulip/zulip-desktop/assets/1593039/70680cef-2494-4e44-a914-b0758dfb28ca)

MacOSX notification for Zulip
![2024-07-06 at 15 07 20](https://github.com/zulip/zulip-desktop/assets/1593039/784e633e-06d5-4a27-9945-d22c60c0868a)


I was under the impression that the red bubble will appear for dock icon, menu bar icon at least.  What's the expected behaviour?
