### ISSUE TITLE
Applications/Zulip.app/Contents/Frameworks/Zulip Helper(Renderer.app) using large memory

### ISSUE THREAD

**Issue by EdYSChuang815** [zulip/zulip-desktop#1116]
**Describe the bug**

I'm using zulip on MacOS 10.13.1. This afternoon I suddenly got a message from my system arguing I'm running out of memory. After I restarted my computer (Zulip starts automatically), I found out from `htop` that `Applications/Zulip.app/Contents/Frameworks/Zulip Helper(Renderer.app)` is using around 40.6G virtual memory. 
(I think it used up all my free space on the SSD hard disk and causing problem)
 
**To Reproduce**

Everytime I open zulip, it happens.

**Screenshots**
<img width="1323" alt="螢幕快照 2021-05-21 下午10 03 00" src="https://user-images.githubusercontent.com/79547206/119193793-78322880-ba82-11eb-85fe-3d0b0edbe7d0.png">

**Desktop (please complete the following information):**

- Operating System:
macOS 10.13.1
- Zulip Desktop Version:
5.7.0

**Comment by andersk** [comment]
Virtual address space is just a range of pointers in which memory *could* be allocated; it doesn’t mean that memory *has* been allocated. The range itself uses essentially no storage, neither in memory nor on disk. Chromium reserves a huge amount of virtual address space for its own convenience. This is just how Chromium works and isn’t a problem.

In `htop`, the actual memory usage in RAM is reported in the `RES` column (although even that can be misleading since shared memory may be reported for multiple processes). Memory that has been swapped from RAM to disk is reported in the `Swp` bar.
