### ISSUE TITLE
libappindicator3-1 not in Debian Bullseye, 5.8.1 .deb not installable

### ISSUE THREAD

**Issue by eMPee584** [zulip/zulip-desktop#1168]
The recent release of zulip depends on `libappindicator3-1` which seems to be an ubuntu-only package, rendering the package impossible to install on current debian. Maybe the `libayatana-appindicator3-1` package can fit the purpose?

**Comment by eXtrem0us** [comment]
According to this [Redit topic](https://www.reddit.com/r/debian/comments/pn1oia/what_happened_to_libappindicator31_in_debian_11/) and this [Debian release note](https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information.en.html#noteworthy-obsolete-packages):

> The deprecated **libappindicator** libraries are no longer provided. As a result, the related packages **libappindicator1**, **libappindicator3-1** and **libappindicator-dev** are no longer available. This is expected to cause dependency errors for third-party software that still depends on **libappindicator** to provide system tray and indicator support.
Debian is using **libayatana-appindicator** as the successor of **libappindicator**.

It seems it would affect Ubuntu releases late or soon... or maybe they're already affected.

**Comment by andersk** [comment]
The upstream fix (develar/app-builder#53) was pulled in by #1178 for v5.9.0.

**Comment by erebion** [comment]
@andersk 

That's the sort of reason the package should be submitted to Debian.

This would also make it available in distributions building on top of Debian, such as Ubuntu and Mint.

This is even the reason why Debian recommends to not use third-party repositories: https://wiki.debian.org/DontBreakDebian

"Don't Break Debian"

```
Some third-party repositories might appear safe to use as they contain only packages that have no equivalent in Debian. However, there are no guarantees that any repository will not add more packages in future, leading to breakage.

Finally, packages in official Debian releases have gone through extensive testing, often for months, and only fit packages are allowed in a release. On the other hand, packages from external sources might alter files belonging to other packages, configure the system in unexpected ways, introduce vulnerabilities, cause licensing issues.

Once packages from unofficial sources are introduced in a system it can become difficult to pinpoint the cause of breakage especially if it happens after months.
```

Please consider uploading to the Debian project.

It even makes installing the client much easier for users as they can just open the software center, type in "Zulip" and click the install button.

**Comment by andersk** [comment]
@erebion As far as we’re concerned, any distro maintainers are welcome to package Zulip Desktop natively in their distro. I even co-maintain the package in NixOS/nixpkgs, and help keep the Homebrew cask updated. An Arch Linux user maintains a package in the Arch User Repository. But this is probably difficult for Debian derivatives since Electron itself is not in Debian, and I would assume that Debian’s policy choice to forbid vendoring (of Electron in Zulip and also of Chromium in Electron) would be an essentially insurmountable obstacle to that effort.

We have plenty of other options for Debian users, such as the [Flathub package](https://flathub.org/apps/org.zulip.Zulip) and [Snap package](https://snapcraft.io/zulip). Or you can install Nix on any Linux distro and run it from nixpkgs. These options are all independent from the system’s shared libraries.

**Comment by erebion** [comment]
@andersk Is the Flathub package official? Because it is not marked as such on Flathub. And I'm hesitant when it comes to installing software where I cannot easily see whether it comes from the devs or not.

If it is official, I'd love to see this get a check mark, so it is easy to see. :)

And I know there are people working on getting Electron into Debian, there are still some dependencies missing. They're making some progress, though.

**Comment by andersk** [comment]
@erebion Thanks for the suggestion. The Flathub package was started by a third party contributor but now I do most of the maintenance. I’ve now added the verification check mark.
