### ISSUE TITLE
Cannot upgrade macos desktop

### ISSUE THREAD

**Issue by ehuss** [zulip/zulip-desktop#1222]
I currently have v5.7.0 installed. When I start the Zulip desktop app, I get a notification that 5.9.3 is available.
<img width="274" alt="image" src="https://user-images.githubusercontent.com/43198/174917180-a5027ee1-56d9-4cf0-889c-4ed19d30dd35.png">
Clicking "Install and Relaunch" causes the desktop app to exit, but it does not restart.
Starting the Desktop app again, it is still on the 5.7.0 version.

I'm not sure where to look for any diagnostic or debugging information. Please let me know if there is more information I can provide.

This has happened on two separate macos systems, one on macOS 11, the other has macOS 12.

In addition, if I say "Install Later" and try to use the "check for updates", the following happens:
1. Tools > Check for Updates
2. Popup says a new version is available and will be downloaded in the background. Click OK.
3. New update popup asks to install 5.9.3. Clicking "Install and Relaunch" closes the popup, and then opens an identical popup.
4. Click "Install and Relaunch" on the second popup closes and restarts Zulip, but it is still on the old version.

**Comment by andersk** [comment]
This is known and was fixed in 5.9.3, but the fix only takes effect when upgrading from 5.9.3 or later.

In order to upgrade to 5.9.3, you can click **Install Later**, then **Quit** from the menu bar and re-open the application yourself. This should allow the automatic upgrade to proceed.

Or you can always download the latest version manually from https://zulip.com/apps/.
