### ISSUE TITLE
No tray icon after update to 5.9.4

### ISSUE THREAD

**Issue by vrozkovec** [zulip/zulip-desktop#1263]
**Describe the bug**

After update to 5.9.4 there is no more tray icon.

**To Reproduce**

Start Zulip, no icon in the tray appears.

**Expected behavior**

Icon in the tray.

**Screenshots**

**Desktop (please complete the following information):**

- Operating System:
Linux Mint 20.3

- Zulip Desktop Version:
5.9.4

**Additional context**

Turning the system tray setting off and back on did not help.

**Comment by alxsimon** [comment]
Same here with the flatpak v5.9.4 under Fedora 37 / Gnome wayland

**Comment by andersk** [comment]
@vrozkovec Are you using the Flatpak as well? This seems to be an issue with the Flatpak packaging. I’m attempting to address it in flathub/org.zulip.Zulip#51. A workaround is to launch the app with

```shell
flatpak run --own-name='org.kde.*' org.zulip.Zulip
```

(although there’s still a display issue: you’ll probably see a **⋯** icon rather than the Zulip icon).

**Comment by alxsimon** [comment]
I can confirm that the workaround works for me. Thanks!

**Comment by andersk** [comment]
I’ve kicked off a Flathub [build](https://buildbot.flathub.org/#/builders/6/builds/15550) that will fix this, though it may take a few hours to make its way through the build queue.

**Comment by daniel-larraz** [comment]
Same issue on Ubuntu 20.04 via Snap.

**Comment by jaroslavpachola** [comment]
Same issue on Ubuntu 22.04 even via AppImage. 5.9.3 works well, no systray icon for 5.9.4.

**Comment by alxsimon** [comment]
Funny the latest Flatpak build also solves the tray icon being ... instead of the real icon.
Thanks

**Comment by vrozkovec** [comment]
> @vrozkovec Are you using the Flatpak as well? This seems to be an issue with the Flatpak packaging. I’m attempting to address it in [flathub/org.zulip.Zulip#51](https://github.com/flathub/org.zulip.Zulip/pull/51). A workaround is to launch the app with
> 
> ```shell
> flatpak run --own-name='org.kde.*' org.zulip.Zulip
> ```
> 
> (although there’s still a display issue: you’ll probably see a **⋯** icon rather than the Zulip icon).

@andersk installed via APT:
`deb https://download.zulip.com/desktop/apt stable main`

**Comment by andersk** [comment]
I tested the AppImage, the deb package, and the Snap package on Ubuntu 20.04.5 and Ubuntu 22.04.1 amd64 live images, and the indicator icon worked in all six combinations. I was able to break it by disabling the **Ubuntu AppIndicators** extension in `gnome-shell-extension-prefs`, so maybe check that if you’re on Ubuntu.

I also tried Linux Mint 20.3 and 21.1 Cinnamon Edition 64-bit, where again the indicator icon worked.

I’ll try some other distros, but if someone can find a specific live image where it reproducibly doesn’t work, that would help narrow down what’s going on.

**Comment by daniel-larraz** [comment]
@andersk You are right. In my case it is Ubuntu 20.04 with GNOME Classic. 5.9.3 works well, no systray icon for 5.9.4.

**Comment by andersk** [comment]
@daniel-larraz Does it work if you enable the **Ubuntu AppIndicators** extension in `gnome-shell-extension-prefs`, then log out of GNOME and log in again? (These are in the packages `gnome-shell-extension-appindicator`, `gnome-shell-extension-prefs`, respectively.)

**Comment by andersk** [comment]
On most non-Ubuntu distros, this same GNOME extension is called **AppIndicator and KStatusNotifierItem Support** with the same [package name](https://repology.org/project/gnome:appindicator/versions) `gnome-shell-extension-appindicator`. It’s also available [from the GNOME extension repository](https://extensions.gnome.org/extension/615/appindicator-support/).

**Comment by jaroslavpachola** [comment]
> On most non-Ubuntu distros, this same GNOME extension is called **AppIndicator and KStatusNotifierItem Support** with the same [package name](https://repology.org/project/gnome:appindicator/versions) `gnome-shell-extension-appindicator`. It’s also available [from the GNOME extension repository](https://extensions.gnome.org/extension/615/appindicator-support/).

I'm using xmonad and stalonetray. Do you still think my configuration can be affected by something like this?

**Comment by andersk** [comment]
@jaroslavpachola I think what you need is [gtk-sni-tray](https://github.com/taffybar/gtk-sni-tray), which can be used standalone or as part of [taffybar](https://github.com/taffybar/taffybar).

**Comment by jaroslavpachola** [comment]
@andersk OK, gtk-sni-tray seems to work, even though I like stalonetray more. What does this mean, does the tray mechanism of this new release of Zulip desktop app work different from previous releases?

**Comment by andersk** [comment]
All we did was upgrade Electron; this new release of Electron and Chromium no longer supports the ancient xembed system tray protocol spoken by stalonetray. That protocol was replaced by KStatusNotifierItem about a decade ago.

**Comment by vrozkovec** [comment]
@andersk 

> I also tried Linux Mint 20.3 and 21.1 Cinnamon Edition 64-bit, where again the indicator icon worked.

I'm using Mate edition, there is XApp Status Applet. Do you have any idea for a fix there? I cannot install `gnome-shell-extension-appindicator` as it would pull all the `gnome-shell`

**Comment by jaroslavpachola** [comment]
> All we did was upgrade Electron; this new release of Electron and Chromium no longer supports the ancient xembed system tray protocol spoken by stalonetray. That protocol was replaced by KStatusNotifierItem about a decade ago.

OK, thanks for your replies, I understand now that the newer Electron forces the new protocol. Configuring taffybar (and the watcher service) is pain, but I hope I'll make it.

**Comment by andersk** [comment]
@vrozkovec I’m not sure about MATE. There’s some possibly related discussion at [LP #1956212](https://bugs.launchpad.net/diodon/+bug/1956212).

**Comment by 1one-w01f** [comment]
I have the same problem on a not-so-clean setup of Xubuntu 20.04 (which was upgraded over the years all the way back from 16.04), on a work machine that I use daily. Zulip v5.9.4 has no tray icons, but downgrading it to v5.9.3 gets the tray icon back.

Interestingly, I tested Zulip v5.9.4 on a freshly installed Xubuntu 20.04 VM and the tray icon is there. On both setups, Zulip was installed via the `.deb` file downloaded from [here](https://github.com/zulip/zulip-desktop/releases).

I suspect it's due to some old indicator libraries/configs on my not-so-clean setup that confused/distracted Electron, but am not sure where to look for the culprit. I checked the app logs (from `Tools`->`Download App Logs`) but didn't see anything related to that. Any pointers would be appreciated. Thanks.

**Comment by daniel-larraz** [comment]
@andersk I would like to clarify that when I run Zulip 5.9.4 on Ubuntu 20.04 with GNOME Classic (installed via Snap), I can see a systray icon for Zulip, but I see this icon ![NoIcon](https://user-images.githubusercontent.com/25650751/211357246-ff7b150d-e653-4afc-983c-d1c51a2beac8.png) rather than the Zulip icon.

If I install Zulip 5.9.4 via Flatpak/APT, or I run the AppImage, I can see the Zulip icon in the tray. So I suspect the problem is not related to the AppIndicator in GNOME Classic but the installation through Snap.

**Comment by andersk** [comment]
@1one-w01f For XFCE, check that you have xfce4-indicator-plugin installed and enabled.

**Comment by 1one-w01f** [comment]
@andersk Thanks for the pointer. I have `xfce4-indicator-plugin` installed on both Xubuntu setups. Confusingly, there are a couple of xfce4-panel items related to tray icons.
![image](https://user-images.githubusercontent.com/35460075/211438096-8e293663-a931-4258-93d2-c32e80074f4a.png)

After some fiddling around, I noticed that on the freshly installed VM, the Zulip tray icon is shown via the "Status Notifier Plugin" instead of the "Indicator Plugin", and in the settings of "Indicator Plugin", there's no "Application Indicators" under "Known Indicators". However, on my daily work machine, the "Application Indicators" is there, which is presumably how I get tray icons for most of my apps. After `sudo apt remove indicator-application`, now I get tray icon from Zulip v5.9.4 shown via the "Status Notifier Plugin" on my work machine.

~~As a user I'm not necessarily happy about the switch to "Status Notifier Plugin". Previously I get by without "Status Notifier Plugin", and just keep "Notification Area" and "Indicator Plugin" enabled. Keeping all 3 leads to further confusions, as several apps will have duplicated tray icons (some can be manually hidden, but that's extra work). Ditching "Notification Area" or "Indicator Plugin" is also not an option, because some tray icons only show up there.~~ After a few restarts, it seems that the duplicate icon problem isn't really that bad. Looks like many apps will prioritize "Status Notifier Plugin" if it is enabled. In any case, this is not the fault of Zulip, and hopefully my experience would be useful to fellow users.

**Comment by nosy79** [comment]
I have the same issue.
Since I have problems with MATE desktop on CentOS 7.9 I tried to find the proper indicator package but was unsuccessful.
Then I tried almalinux 9 with mate, no luck, too. 
Probably I still dont know how the package is called.
On Ubuntu 22.04 it is working for 5.9.4  but not on Debian 11 with MATE desktop and the mate-indicator package.

**Comment by andersk** [comment]
For reference, this is where the tray icon implementation changed in Electron:

- electron/electron#36333

(**Note:** don’t spam the Electron issue tracker with support requests. Although zulip-desktop uses Electron, the Electron project is completely separate and won’t be able to help you with Zulip issues.)

**Comment by vrozkovec** [comment]
@andersk thanks for the pointer. I've checked the discussion but no solution there applies/works.
I've tried all different kind of notification areas but none of them shows the icon.
For now I've given up and reverted back to 5.9.3 for the time being.

**Comment by jaroslavpachola** [comment]
In case anybody uses a tiling manager, esp. xmonad and runs into the problem with missing tray icon with new Zulip version: polybar doesn't work, taffybar works but leaks memory horribly (YMMV). What works for me is "xfce4-panel --disable-wm-check". Integrates legacy tray icons and d-bus based tray icons and seems to be reliable and lean enough.

**Comment by andersk** [comment]
I’ve released Zulip Desktop 5.9.5 based on Electron 22.2.0, which includes an upstream change that might allow the tray icon to work in legacy desktop environments again (electron/electron#37034).

**Comment by jaroslavpachola** [comment]
> I’ve released Zulip Desktop 5.9.5 based on Electron 22.2.0, which includes an upstream change that might allow the tray icon to work in legacy desktop environments again ([electron/electron#37034](https://github.com/electron/electron/pull/37034)).

Works for me (in Stalonetray). Thanks a lot!

**Comment by vrozkovec** [comment]
> I’ve released Zulip Desktop 5.9.5 based on Electron 22.2.0, which includes an upstream change that might allow the tray icon to work in legacy desktop environments again ([electron/electron#37034](https://github.com/electron/electron/pull/37034)).

Issue is fixed for me as well (Linux Mint 20.3, Mate edition). Thank you!

**Comment by nosy79** [comment]
Great :) Tray icons work on CentOS 7.9 now. Ubuntu 22.04 is still working.
