### ISSUE TITLE
Zulip version 5.10.1 crashes on Ubuntu 20.04.6 LTS

### ISSUE THREAD

**Issue by rbommel** [zulip/zulip-desktop#1327]
**Describe the bug**

After a few minutes the window shows a gray background and a program crashed dialog shows up.

**To Reproduce**

Just start Zulip and wait for a bit.

**Expected behavior**

Zulip doesn't crash.

**Desktop (please complete the following information):**

- Operating System:
Ubuntu 20.04.6 LTS
- Zulip Desktop Version:
5.10.1

**Additional context**

Downgrading to 5.10.0 solves the problem.

**Comment by Rusty-Weasel** [comment]
**Describe the bug**
After a few **seconds** the window shows a **white** background and a program crashed dialog shows up.

**To Reproduce**
Just start Zulip and wait for a bit.

**Expected behavior**
Zulip doesn't crash.

**Desktop (please complete the following information):**

- Operating System:
Manjaro latest with Kernel 6.5.1-1
- Zulip Desktop Version:
5.10.1 (AppImage)

**Additional context**
Downgrading to 5.10.0 solves the problem.

![image](https://github.com/zulip/zulip-desktop/assets/61587283/f22caef8-4dda-402c-9a79-526628cbb145)

**Comment by ympek** [comment]
Hello. 
I have the same issue on Mint 21.2
5.10.1 release is broken.

**Comment by Quasar6X** [comment]
Hello,
Same happens on Ubuntu 23.04, kernel 6.2.0. Had to revert to version 5.10.0
