### ISSUE TITLE
Improve Internet disconnectivity error page 

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#157]
someone reported this issue - 
> half the time when I lose internet connectivity and regain it, or close/open my laptop, zulip spins forever and I have to kill it and restart it.

![image](https://cloud.githubusercontent.com/assets/2263909/26474317/280d82f4-4165-11e7-808b-42f3e9c7ce8c.png)

**Comment by timabbott** [comment]
I confirmed he was using master as of monday.

**Comment by akashnimare** [comment]
The actual cause of this error is that the [function](https://github.com/zulip/zulip-electron/blob/master/app/main/index.js#L70) we wrote for checking the internet connectivity and showing the try again dialog is not getting called.

**Comment by timabbott** [comment]
Did we end up reverting that?  I think the try again dialog isn't helpful; we should either auto-reload or not, as the case may be.

**Comment by Lplenka** [comment]
I am quite sure PR [#147](https://github.com/zulip/zulip-electron/pull/147) fixed this issue. App used to auto-reload after resuming from sleep.
Have not checked it though after merging PR[#140](https://github.com/zulip/zulip-electron/pull/140). Will verify and try to find a fix. :smile:

**Comment by Lplenka** [comment]
Found the error, working on it 😁

**Comment by zhongyi-tong** [comment]
@Lplenka @akashnimare Hey guys, we are running each Zulip domain in a webview. So changing `mainWindow.webContents.on('did-fail-load'...` won't help if contents in the webview failed to load.

I'm starting a new PR to fix this. Besides this listener, we should also watch network connectivity, to reload the app when network is back again.

**Comment by zhongyi-tong** [comment]
Fixed according to #165 .

> When internet is disconnected, a dialog shows, which allows the user to reload the web contents.
>
> This is a hotfix. More refinements on network monitor and recovery will come in a separate PR. 
> 
> <img width="532" alt="screen shot 2017-06-01 at 7 34 29 pm" src="https://cloud.githubusercontent.com/assets/7262715/26678084/627623be-4701-11e7-988a-dafb82e2af86.png">

**Comment by timabbott** [comment]
I think from a user experience perspective, that sort of popup is annoying; as a user, you either are now on the Internet (and probably want it to automatically reload when it detects the network is back up, with perhaps a "reload" button next to the loading spinner in the screenshot at the start of this issue for manual adjustment) or you aren't (and don't want the popup).

Is that easy to do @geeeeeeeeek?

**Comment by zhongyi-tong** [comment]
@timabbott Yep, agreed. Easy to do so. There needs to be some changes in UI. But I prefer to refactor some code before we move on to this feature. Maybe in this weekend when others are afk? However this PR can be merged as a temporary fix.

There is a good point using an alert at the moment. Since the current code continuously checks after failure, the alert will block the execution of the following code to avoid running into a infinite loop. It's not user friendly though :)

What I think we should do, after disconnected:
 - Show an error page in the right WebView area. Display the Error message (ERR_NAME_NOT_RESOLVED, etc) with a huge reload button on screen.
 - When wifi reconnects, automatically try to regain connection.
 - A permanent reload button on the bottom of the left sidebar, which is used to reload the active webview at any time the user wants.

**Comment by timabbott** [comment]
that plan sounds reasonable to me.

**Comment by zhongyi-tong** [comment]
As #165 merged, should we close this? It's no longer breaking.

**Comment by akashnimare** [comment]
Instead of showing the error dialog we should redirect user to an error page, something like slack does -

![screen shot 2017-06-08 at 2 14 30 pm](https://user-images.githubusercontent.com/2263909/26919941-07d9f5da-4c55-11e7-9213-0b69601ac642.png)

![screen shot 2017-06-08 at 2 14 50 pm](https://user-images.githubusercontent.com/2263909/26919953-12159022-4c55-11e7-9e2c-f0cea0d9d346.png)

**Comment by zhongyi-tong** [comment]
@akashnimare Sounds great. Will do in the next several days.
