### ISSUE TITLE
improvement: Windows taskbar icon notification like Skype

### ISSUE THREAD

**Issue by penCsharpener** [zulip/zulip-desktop#167]
In windows the sys tray icon is too often hidden at the moment, and the number of unread msgs is tiny. 

The legacy had this wonderful number in the taskbar icon. Please add this also in Electron app because in a multi-monitor setup we miss a lot of message due to this.

**Comment by Lplenka** [comment]
The features of our app will be limited to the capabilities of the upstream [electron](https://github.com/electron/electron). **There is no support to show unread count in the taskbar (also not in the tray) in the upstream [electron](https://github.com/electron/electron)** for now. We have added the functionality to show unread count in the tray.

Since you are facing the problem with the size of the tray icon. We have to show unread count in the taskbar. 
Looking for possible ways :sweat_smile: .

**Comment by penCsharpener** [comment]
Would it be worth submitting a request issue in the electron repository?
What version of electron is zulip app using right now? Maybe the feature is there in electron but not the version zulip is built on.

there are more limitations with having notifications just in the tray: 
on a multi-monitor setup the tray is not duplicated to secondary screen even if your settings say that you want the taskbar duplicated. ie. I use three screen most of the time ...

**Comment by Lplenka** [comment]
@vbNETonIce  feel free to open issues there.
I also created this issue [https://github.com/electron/electron/issues/9020](https://github.com/electron/electron/issues/9020)

Currently we are using `1.6.8` version of electron. yes we are behind. There were some newer verions released a couple of days ago.

**Comment by timabbott** [comment]
This is probably worth doing some nontrivial investment in creating, after we've fixed the more critical bugs we're aware of.

**Comment by ElliotSilver** [comment]
The linked electron issue indicates other apps are generating icons on the fly, which, in the absence of an actual API, seems like a reasonable solution.

This is the primary issue that has been holding me back from switching from the old desktop app to the electron one. 

I usually have ~20 or so applications in the task bar, and minimal icons displayed in the notification area (so that I can see all 20 applications).  I could show the Zulip icon in the notification area, but I'm already giving Zulip space in the taskbar, so I'd much rather it use that space.

**Comment by timabbott** [comment]
Increasing the priority on this, since it sounds like it's a blocker to migrating for a number of people.

**Comment by penCsharpener** [comment]
Thanks Tim, we basically forced everyone to use the electron app but we had many long faces when they didn't have the taskbar notifications anymore from the legacy app. And with multi-monitor setups many still complain about missing msgs. If this can be done it would be a major step forward!

**Comment by penCsharpener** [comment]
for future reference some electron messengers that have taskbar notifications:
inofficial whatsapp claims to have it: https://github.com/bcalik/Whatsapp-Desktop
official wire: https://github.com/wireapp/wire-desktop (although I have to check it again. 

but electron also has some documentation about overlaying the taskbar icon
[overlay icon with image](https://github.com/electron/electron/blob/master/docs/tutorial/desktop-environment-integration.md#icon-overlays-in-taskbar-windows)

[flashing the taskbar icon](https://github.com/electron/electron/blob/master/docs/tutorial/desktop-environment-integration.md#flash-frame-windows)
with only few lines of code this could be easy to implement, wouldn't it?

so it looks like Electron is supporting those notifications. 😃

**Comment by akashnimare** [comment]
@vbNETonIce thanks for above links. I'll look into it :)

**Comment by akashnimare** [comment]
This feature has been added in https://github.com/zulip/zulip-electron/commit/67dc1e2a11ab7b573776ccaa90656b8051e57124. This is how it looks -
![pasted_image 2](https://user-images.githubusercontent.com/2263909/28446339-c527bd8a-6de7-11e7-8ef5-65e76fc6648c.png)

@vbNETonIce, @ElliotSilver can you verify if it works properly.

**Comment by penCsharpener** [comment]
you nailed it! Looking great and it's eye catching. Well, I guess it  was a few more lines of code than my 3, haha. 
![flash and overlay](https://user-images.githubusercontent.com/26190934/28449543-207b3e5c-6de1-11e7-98e6-702290cc650d.gif)

**Comment by akashnimare** [comment]
@vbNETonIce Thanks, I told you it's just a matter of time. @ElliotSilver feel free to migrate to [zulip-electron](github.com/zulip/zulip-electron/releases) :)
