### ISSUE TITLE
Reload/refresh button should have a tooltip

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-desktop#207]
In the lower left, just above a gear icon, there's a circle-arrow "reload" icon. It's not obvious just what that's supposed to do; if nothing else, it should have a short tooltip.

On clicking it, it appears to reload the webview. That seems like something the user shouldn't have to do -- if they do that and it helps them, whatever issue it was resolving for them was a bug. And at least in a browser I think it's currently pretty rare for us to have a bug like that -- I think the only times I've benefitted from reloading a Zulip tab have been when it didn't handle a network change, due to the issue mentioned in https://github.com/zulip/zulip/issues/5598 . So I'm curious how often people who've been using the app feel like they're doing that.

**Comment by akashnimare** [comment]
> Zhongyi  - The reload button is still useful I think. In some cases, e.g. when app reloads on network reconnected, but somehow before DNS resolution is ready, the page will be blank and users need to reload the page manually.

Adding to this I think that reload button is necessary for now. We don't want a situation where a white blank page shows up (due to network issues etc) and the user has no idea what to do at that moment. Mostly a quick reload fixes everything. 

Ideally, the app should be able to auto-reload itself. We're trying to figure out those cases when the white page shows up. We'll remove this reload button in future. Just to make it clear I have added a tooltip.

![awesomescreenshot-2017-07-18t17-58-50-413z](https://user-images.githubusercontent.com/2263909/28332534-c9077700-6c12-11e7-9609-cb55008f51fb.gif)

**Comment by akashnimare** [comment]
@gnprice thanks for the suggestions, closing this now.
