### ISSUE TITLE
Performance issue on Linux when closing keyboard shortcuts overlay

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#242]
In the app on Linux (current master), I can reliably reproduce hitting `?` working fine, but then hitting then `escape` to close the keyboard shortcuts modal is really slow; it feels like it takes like half a second.  

Here's a profile obtained using the developer tools:
![image](https://user-images.githubusercontent.com/2746074/28846203-6e9aa0aa-76bf-11e7-9425-4add03013bf1.png)

Since the issue doesn't happen on web, I wonder whether the issue is that we're somehow not taking advantage of the GPU or something when doing rendering in the electron app?  I don't see another reason why layouts would be so much slower than in Chrome.

**Comment by zhongyi-tong** [comment]
After some profiling work, I found out that `resize_bottom_whitespace ` took unreasonably long time, which was recalculating layout and rendering. DevTools suggest it might be caused by a forced reflow.
<img width="801" alt="shortcuts2" src="https://user-images.githubusercontent.com/7262715/28884551-e4d7f5a2-7777-11e7-9028-b91bdb2ba898.png">

On contrast, closing a settings overlay won't have such issue. I don't quite understand why. I will take a deeper look tomorrow.
<img width="802" alt="settings2" src="https://user-images.githubusercontent.com/7262715/28884572-f5ac5a80-7777-11e7-82ff-7ea324e5eafe.png">

**Comment by zhongyi-tong** [comment]
I tried to diff the behaviors on each side and here is what I found. After clicking the close button, 

In Electron (628ms in total):
 - 252ms to recalculate style
 - 212ms to layout
 - 164ms to update layout tree

In Chrome (55ms in total):
 - 6ms to recalculate style
 - 4ms to layout
 - 45ms to update layout tree

I googled some other cases but still couldn't find an exact cause. Might need an extra pair of hands on this.

**Comment by akashnimare** [comment]
628ms is massive. We gotta find out what's going on with Electron.

**Comment by abhigyank** [comment]
This issue seems to be solved due to an electron update. Discussed [here](https://chat.zulip.org/#narrow/stream/16-electron/subject/perf/near/553954)

ping @akashnimare . Close this?

**Comment by akashnimare** [comment]
Let me first double check this!

**Comment by akashnimare** [comment]
`escape_key` event takes 7.7 ms on electron and 7.2 ms on chrome so I think we're good here.
