### ISSUE TITLE
Weird size flicker when opening the app or an existing Zulip organization

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#249]
If you close the app and then re-open it, and then click on a busy organization like chat.zulip.org, there's a brief flicker as it loads the page where the right-side window area is super small, like this:

![image](https://user-images.githubusercontent.com/2746074/28847394-ea1b6f9e-76c3-11e7-9752-5382ce45800c.png)

It'd be awesome to get rid of this, since it doesn't look super good.

**Comment by zhongyi-tong** [comment]
Fixed in #256.

`<webview>` runs out of the process, so the asynchronous nature is by design. The laggy resizing bug is described [here](https://bugs.chromium.org/p/chromium/issues/detail?id=639867). It's a bug from Chromium and has not been fixed.

The workaround is to use an exponential ease-in animation to make the opening looks smooth. The time of opening a new tab is increased by 0.7s, which is acceptable, and reopening an opened tab will not be affected.

**Comment by akashnimare** [comment]
@timabbott can you reproduce this on master?

**Comment by timabbott** [comment]
The workaround works mostly, though I'm not really a fan of the 0.7s delay.  It might be worth asking on Electron forums about whether there's a better workaround available; other Electron apps like Slack seem to not have this problem...

**Comment by akashnimare** [comment]
Looks like the flickering issue is an upstream bug -
https://github.com/electron/electron/issues/8127
https://github.com/atom/atom/issues/15544

**Comment by akashnimare** [comment]
FYI, @timabbott.

**Comment by timabbott** [comment]
Yay, thanks @akashnimare!
