### ISSUE TITLE
Focus doesn't work properly on Linux/Windows

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#251]
On Ubuntu 16.04, with the master branch, if you alt-tab to the window, you need to click into the window in order for any of our keyboard shortcuts to work, which is pretty annoying.

**Comment by gnprice** [comment]
I've been seeing the same thing today -- on Debian stretch, running GNOME.

**Comment by gnprice** [comment]
I've been seeing the same thing today -- on Debian stretch, running GNOME.

**Comment by zhongyi-tong** [comment]
I didn't reproduce this issue on the master branch. 

Steps:
1. Focus on another app (terminal).
2. Alt-tab to Zulip.
3. Ctrl+1 -> Switch to first tab.
4. Ctrl+=/Ctrl+- -> Zoom in/out webview.

![2](https://user-images.githubusercontent.com/7262715/28855248-7c16f85e-7701-11e7-96b4-934cfbbc4127.gif)

**Comment by gnprice** [comment]
Interesting.

Instead of alt-tab, try mousing over the Zulip app? Or clicking on the
title bar.

For me the issue reproduces on any of mouse over (which I've set my window
manager to cause the window to be focused), click title bar, ​or alt-tab.
Only clicking inside the window succeeds in making the keyboard shortcuts
start working again.

**Comment by akashnimare** [comment]
I can't reproduce this either. @timabbott, @gnprice can you check if following steps works on your system -
> Focus on another app (terminal).
> Alt-tab to Zulip.
> Ctrl+1 -> Switch to first tab.
> Ctrl+=/Ctrl+- -> Zoom in/out webview.

**Comment by gnprice** [comment]
​Those steps work fine. Ctrl-= and Ctrl-- successfully zoom the view, but
the webapp's shortcuts (even up/down to move between messages) have no
effect.

**Comment by akashnimare** [comment]
Okay, I can reproduce this now. I thought you guys were talking about the desktop shortcuts (Ctrl+1, Ctrl+= etc) which work on `Alt+tab`. @geeeeeeeeek try reproducing this using `J` and `K` which does not work when the window loses focus. I confirm that it's caused by https://github.com/zulip/zulip-electron/pull/241. The problem is when you focus other app and get back to Zulip using `Alt + tab` the browser window gets focus not the webview and that is why one has to click within the webview for the focus.

**Comment by akashnimare** [comment]
@geeeeeeeeek we need to find a solution which fixes this as well as #216.

**Comment by akashnimare** [comment]
Can you guys pull up [window-focus-fix](https://github.com/zulip/zulip-electron/tree/window-focus-fix) and check if this fixes #216 + #251?

Update - Well, it does not work as expected 😭

**Comment by akashnimare** [comment]
I have pushed a fix again. I'm sure it should fix #216 + #251 😞 
Can you guys please check again using [window-focus-fix](https://github.com/zulip/zulip-electron/tree/window-focus-fix)?

**Comment by akashnimare** [comment]
Fixed in https://github.com/zulip/zulip-electron/commit/20feb9bd388d946ce4e6f9478c762ad32de3e27a.

**Comment by timabbott** [comment]
I verified it's working well for me.  :tada: :rocket:

**Comment by gnprice** [comment]
Works for me -- thanks @akashnimare !
