### ISSUE TITLE
Add certificate related issues in troubleshooting guide

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#325]
Someone just reported that they were getting the "Not a valid Zulip server" errors when trying to use it on Windows 7.  I suspect the issue they need a proxy to access the Internet, and didn't realized they needed to set this up.

I think we should expand the "Not a valid Zulip server" error message to something more user-friendly that will help them debug.  The simplest version would be just to change the text to something like:

"https://zulip.example.com does not appear to be a valid Zulip server.  Make sure that (1) you can connect to that URL in a web browser and (2) if you need a proxy to connect to the Internet, that you've configured your proxy in the "Network" settings".

**Comment by alexandrul** [comment]
Is there a troubleshooting guide?

I have installed a zulip server on a local VM (with network in bridged mode), I can use it in the browser, however the desktop app still can't connect to it.

In devtools there are no error messages in the console tab, nor any activity in the network tab.

On the same machine I'm using  VS Code just fine.

**Comment by alexandrul** [comment]
The workaround specified in #25 works in my case for the internal server.

For external servers I had to define the `http_proxy` and `https_proxy` env vars, since the proxy settings defined in the application were ignored.

**Comment by timabbott** [comment]
@alexandrul glad to hear you got it working.  @akashnimare I think we should probably worth working on both debugging this and adding a "network troubleshooting" guide, maybe in the /help/ site, that we can point users to.

**Comment by akashnimare** [comment]
Yeah, we can put the network troubleshooting section in our [troubleshooting guide](https://github.com/zulip/zulip-electron/blob/master/troubleshooting.md). Also, we need to move it to `/help/` site.

**Comment by alexandrul** [comment]
Is it possible to also show the actual error when failing to connect instead of a check list with possible causes?

E.g.: connectivity failures (check URL and/or proxy settings), certificate validation issues, and so on.

**Comment by akashnimare** [comment]
We already show an error dialog if there is certificate validation issue.

**Comment by alexandrul** [comment]
In my case, in both cases (internal server & external server) I have received only the "Not a valid Zulip server" message.

Only by chance I was able to find the `NODE_TLS_REJECT_UNAUTHORIZED` workaround and start using the desktop client.

**Comment by akashnimare** [comment]
@alexandrul https://github.com/zulip/zulip-electron/issues/325#issuecomment-341144399 and https://github.com/zulip/zulip-electron/issues/325#issuecomment-341115133 will be fixed once #126 is done.

**Comment by alexandrul** [comment]
Thank you for the good news.

**Comment by GrumpyOldTroll** [comment]
Regarding the claim "We already show an error dialog if there is certificate validation issue.":

I'm currently seeing the error message from domain-util.js, line 172 ( https://github.com/zulip/zulip-electron/blob/aa8e99b7a629062e5360bbabd3367815ad02073a/app/renderer/js/utils/domain-util.js#L172 ), but on further investigation it seems that it's only checking for 3 specific error strings, configured on line 118.

In this failing "else" case, would it be reasonable to surface the actual error message contained in "error" instead of (or in addition to) suggesting that it's one of the 3 listed things?

**Comment by GrumpyOldTroll** [comment]
PS: I discovered today that it worked to manually edit (on Mac) ~/Library/Application\ Support/Zulip/domain.json to contain (instead of "{}"):
{
    "domains": [
        {
            "icon": "../renderer/img/icon.png",
            "url": "https://zulip.example.com/accounts/login/sso/",
            "alias": "https://zulip.example.com/accounts/login/sso/"
        }
    ]
}

After this edit, my app works successfully (keychain wanted my cert's password, and the app gave me correct content afterward), but none of the following worked as an entry for the "Add Organization" button:
- https://zulip.example.com/accounts/login/sso/
- https://zulip.example.com
- zulip.example.com

I hope that's helpful.

**Comment by andersk** [comment]
Closing since certificates work completely differently now (which is to say, they work) and we have documentation at:

https://zulip.readthedocs.io/en/stable/production/ssl-certificates.html
https://zulip.com/help/custom-certificates
