### ISSUE TITLE
osx: no way to disable Zulip from starting on Login

### ISSUE THREAD

**Issue by JoeJasinski** [zulip/zulip-desktop#334]
After installing Zulip Desktop 0.5.2 on Mac OSX 10.13.1 (and prior versions), the application starts automatically on login.  A zulip icon appears as a menu in the top menu bar in OSX.  This menu offers no means to disable auto-start on login.  I'm having difficulty determining where this application launches and how I can disable it from doing so automatically.  No entry appears in the "LoginItems" tab under the "Users and Groups" preference pane.  In addition, there was no obviously named plist in any of the following directories:
  - /System/Library/LaunchDaemons/
  - /System/Library/LaunchAgents/
  - /Library/LaunchAgents/
  - /Library/LaunchAgents/
  - ~/Library/LaunchAgents/

It should be easier to configure this autostart behavior.

**Comment by akashnimare** [comment]
@JoeJasinski are you sure that you're using `v0.5.2`? The current stable version is v1.5.0. In the latest release there is a setting option to disable/enable this feature.

![image](https://user-images.githubusercontent.com/2263909/32719054-07c0016e-c885-11e7-9fc1-67a721575665.png)



 Download it from - https://zulipchat.com/apps

**Comment by timabbott** [comment]
@JoeJasinski how did you end up with 0.5.2?  That version is super old and actually a completely different app implementation.  Try uninstalling the old app and downloading 1.5.0 from https://zulipchat.com/apps/.  

(I'm closing this issue since it doesn't apply to this project; it applies to the old zulip-desktop-legacy project, so there's nothing we can do to address it here)

**Comment by JoeJasinski** [comment]
Thank you @timabbott and @akashnimare. I'll try with a newer version.
