### ISSUE TITLE
Send a notification when a new update available [Debian]

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-desktop#398]
This could be done easily using the `update-available` event of [autoupdater](https://www.electron.build/auto-update) but we need to first check whether it's supported by electron-updater or not.

**Comment by akashnimare** [comment]
I had a chat with the developer of electron-builder and he said there is no plan to add this feature in near future so we gotta add this on our own. 

Potential solution - Add a script to get the latest release from GitHub and then compare it to the installed version.

**Comment by abhigyank** [comment]
I'd like to work on this. Where should the script be added?
I am thinking of working on the solution you suggest. With github API we can get the latest release version and compare it with `app.getVersion()` .

**Comment by akashnimare** [comment]
I think it should be added somewhere in `app/main/`.

**Comment by abhigyank** [comment]
Isn't auto updates already being done [here](https://github.com/zulip/zulip-electron/blob/master/app/main/autoupdater.js) using `electron-updater`?

**Comment by priyank-p** [comment]
@abhigyank yep its done there but the real issue is that on debian electron-updater does not work and that way we need you do it use a github api. Does that make sense?

Generally if have other question post them at [#electron](https://chat.zulip.org/#narrow/stream/electron) it work better there, since you can more in detail answer for what you looking for :)
