### ISSUE TITLE
Organization name does not update on the sidebar

### ISSUE THREAD

**Issue by anurag1018** [zulip/zulip-desktop#425]
---

- **Operating System**:
  - [ ] Windows
  - [ ] Linux/Ubutnu
  - [x] macOS
![zulipelectronbug](https://user-images.githubusercontent.com/17769227/36432456-40a80dac-1680-11e8-9a6b-3e5320c0cc2e.gif)

Upon changing the Organization's name and icon, they are not instantly updated on the sidebar. I tried logging out and back in but still the bug persists. 
The only way to get the name and icon updated is to delete and re add the organization from the app Settings>Servers page.

**Comment by akashnimare** [comment]
Yeah, it takes time to load. You gotta reload app to see the changes. We basically fetch and save the icon URL on the first load/hard reload etc.

**Comment by timabbott** [comment]
@akashnimare if we had a hook mechanism for webapp code calling into the Electron app, it'd be easy to make this work.  I think we should think about designing something like this.  E.g. the old desktop app had a `window.bridge` defined in the app.  For the Electron app, the webapp code could do e.g.
```
if (window.electron_bridge !== undefined && window_electron_bridge.update_org_name !== undefined) {
    window_electron_bridge.update_org_name(new_name);
}
```

inside the handler for the webapp receiving an event update from the server that the organization name had changed.  (Or maybe a slightly different API, but we need to deal with cases where either the webapp or the Electron app is newer, so that sort of feature detection is probably a good idea)

(And the Electron app would just have an object it would add to the window, `window.electron_bridge`, which we would attach functions to for features like this.

I think this is a good simple mechanism that we could do for the first use of this, but once we have it working, we can switch a lot of other things (unread count data, etc.) to use it rather than ugly things like parsing the title bar.

**Comment by akashnimare** [comment]
I agree that we should use this kind of approach to pass the data from webapp to electron app.

**Comment by timabbott** [comment]
OK.  @akashnimare do you want to try doing the exact interface I described above, and do PRs to this repo and the zulip/zulip one for this feature?  I think it's worth getting this protocol worked out soon, so that we can use it for the next N features.

**Comment by timabbott** [comment]
@cPhost do you want to work on this using the `electron_bridge` approach?

**Comment by priyank-p** [comment]
I am working on it. I was looking for code on webapp that does this but did get chance to dig more into the codebase.

**Comment by abhigyank** [comment]
@zulipbot  claim
