### ISSUE TITLE
Dockerized the development environment

### ISSUE THREAD

**Issue by blinfoldking** [zulip/zulip-desktop#447]
i think we could add a Dockerized option for developement where everyone would have the same environment regardless of the OS

**Comment by akashnimare** [comment]
@BlinfoldKing I'm not sure if it's a good idea, especially in the cross-platform development. The more platform the app is tested the better it is so it shouldn't be dockerized. We can't provide a single docker image for all the platforms since I don't think it provides any kind of UI. IMO, Docker is better for server-side things. 
That being said, if you want to give it a try feel free to do it. Maybe try the vagrant image or something. In any case, we need to provide different images for all the platforms (because of the UI restrictions).

cc @timabbott, @gnprice.

**Comment by blinfoldking** [comment]
i see, thanks for your opinion

**Comment by akashnimare** [comment]
@BlinfoldKing let me know if you're willing to work on #145 which will certainly make the development process better.
