### ISSUE TITLE
Inappropriate "Not a Zulip Server" error with locked-down hosts

### ISSUE THREAD

**Issue by hlieberman** [zulip/zulip-desktop#46]
When attempting to connect to a Zulip server that requires authentication to access any content, not just the dynamic endpoints, the client inappropriately interprets a request for authentication as an error at app/renderer/js/main.js@18 and app/renderer/js/pref.js@26.

This function should be extracted out into one place and extended.

**Comment by akashnimare** [comment]
Btw what server address you'r trying. Could you give me testing server address?

**Comment by hlieberman** [comment]
I can't, unfortunately, because it's behind a firewall.  However, to test, add a requirement for HTTP basic authentication to the entire Zulip vhost, and then point zulip-electron at it.

**Comment by timabbott** [comment]
@akashnimare maybe the right solution is that if we get an HTTP response indicating a request for authorization when trying to verify the zulip server, we assume the server is OK and proceed to trying to login?

**Comment by akashnimare** [comment]
Merging it here https://github.com/zulip/zulip-electron/issues/25

**Comment by timabbott** [comment]
It sounds like this may have regressed.

**Comment by timabbott** [comment]
We should probably add a test for this condition when we fix it...

**Comment by akashnimare** [comment]
The logic behind **zulip server checking** works quite well in most of the cases but there are few exceptions such as https://github.com/zulip/zulip-electron/issues/25, localhost etc where it fails. We should definitely write some tests to check those conditions.

**Comment by timabbott** [comment]
OK, so I think we have two possible designs for this.

1. The app should, when checking if a Zulip server is valid via the `/server_settings` endpoint (or getting `zulip.ogg`), if it receives an HTTP response requesting authorization, just treat that as a "this is a valid server" response.  This is kinda annoying because we want to be able to set an icon when we validate the server
2. Zulip servers that are configured to require authorization for every URL should expose the `/server_settings` endpoint so that the desktop (and mobile) apps can register the server and set an icon before the user is required to send authentication credentials.  

@hlieberman in your environment, would option 2 (exposing a no-authentication-required endpoint without login) be a possibility?  I think it'd just take a couple lines of apache/nginx configuration.

**Comment by timabbott** [comment]
@jwedoff would you be able to track down an answer on this?

**Comment by akashnimare** [comment]
@hlieberman this should work in the latest release [v1.4.0](https://github.com/zulip/zulip-electron/releases/tag/v1.4.0). If you're behind a proxy, you can config it using `Setting page > Network`. Please try the latest release and let me know if it works.

**Comment by timabbott** [comment]
@jwedoff can you have someone test this?
