### ISSUE TITLE
Control-[ stopped working to dismiss the new message entry box?

### ISSUE THREAD

**Issue by glyph** [zulip/zulip-desktop#489]
The issue is just what it sounds like: <kbd>control</kbd><kbd>[</kbd> used to be a synonym for <kbd>esc</kbd> and now it doesn't seem to be (it does nothing), despite the <kbd>?</kbd> dialog box still saying `Esc, Ctrl + [ | Cancel compose`

This as of v2.2.0-beta.

**Comment by abhigyank** [comment]
<kbd>Ctrl/Cmd</kbd>+<kbd>[</kbd> is a webapp shortcut and it has not been deprecated so this should work for you. I am unable to reproduce this on both Ubuntu and macOS High Sierra. Can you confirm since when is this not working for you? Could you also possibly try this on the webapp and see if it works or doesn't work for you there?
Also is the `Esc` key working for you?

**Comment by timabbott** [comment]
This is almost certainly a webapp issue.  @glyph I think this might have been accidentally switched to `Cmd + [` as part of adding a new keyboard shortcut that should definitely be `command + K` on Mac and `Ctrl + K` on everything else; which is correct?

**Comment by akashnimare** [comment]
Yeah, it's a web app issue. Re-opened here - https://github.com/zulip/zulip/issues/9525.
