### ISSUE TITLE
Adding a new organisation must prepend https in order to connect

### ISSUE THREAD

**Issue by pflueg** [zulip/zulip-desktop#520]
When adding a new organisation, the client stucks at "connecting", when you do not prepend the url with "https://".
The client probably tries a non-secure connection first and got a way too big timeout for that.

It would be way more convenient, when the client tries the secure connection first, without forcing the user to prepend the https him- or herself.

---

- **Operating System**:
Ubuntu 18.04
- **Clear steps to reproduce the issue**:
Add new organisation and add url without "https://" - like "zulip.example.com"
- **Relevant error messages and/or screenshots**:
![connecting](https://user-images.githubusercontent.com/34553498/42806171-114c9892-89ae-11e8-9256-a126f4f874a8.png)

**Comment by abhigyank** [comment]
If the URL is not prepended with https, we manually add https before adding the organization. Such that there is no difference between entering https://chat.zulip.org and only chat.zulip.org

**Comment by pflueg** [comment]
Ok - but as you can see in the screenshot the client is still stuck when only entering "chat.zulip.org" without "https://"

**Comment by abhigyank** [comment]
This [piece of code](https://github.com/zulip/zulip-electron/blob/master/app/renderer/js/utils/domain-util.js#L299) prepends the https. 
@pflueg Are you able to add the server with https://chat.zulip.org and not with only chat.zulip.org? 
Are you behind a proxy? This could also be because of the proxy not handling the request properly.
It'd be helpful if you can show what you have in your the content of your console (`View -> Toggle DevTools for App` ) when you feel it has timedout.

**Comment by akashnimare** [comment]
@pflueg the other possible reason could be the slow internet connection. Would be great if you could provide more details on this.

**Comment by pflueg** [comment]
Hi everyone - thanks alot for the hints. I tried it on different telephone lines and indeed it a slow connection might be the reason. Maybe you can add some status in the button like "connected", "waiting for connection" etc.

I am closing the issue for now, since the functionality is fine
