### ISSUE TITLE
Enterprise management feature

### ISSUE THREAD

**Issue by ygini** [zulip/zulip-desktop#527]
**Operating System**:
  - [x] Windows
  - [x] Linux/Ubutnu
  - [x] macOS

**Requested feature**:

Maybe I didn't found it, but it look like Zulip does not support enterprise management scenario.

For all OS and with a method appropriate for each of them, an enterprise configuration profile must be supported.

On macOS it must be MCX based to be compatible with MDM

On Windows it must be GPO or MDM based

On Linux it must be system side file based

Each of this solution must allow IT in a business deployment solution to manage:
- the default server (provide URL and set Zulip to automatically advance to the login step)
- the right to add other servers or not

**Comment by akashnimare** [comment]
@timabbott do you have any idea about this?

**Comment by timabbott** [comment]
Yep!  This is definitely a category of instructions we'll want to provide: Basically how to install the Zulip desktop app on every machine at a company, with some system-level configuration (i.e. stuff in /etc/ in Linux is what he means by "system side file") that can control how the app behaves.  The ideas @ygini mentioned are very much in line with the types of things folks want other products like Dropbox to support for deployment at enterprises.

I'm not personally familiar with the OSX/Windows technologies that folks use for this; @ygini do you happen to have links to guides on those handy?  

If we wanted to start working on this, I'd begin with the spec for Linux (just because it'll involve thinking through most of the issues):

---------------------

If a certain file, say, `/etc/zulip-desktop.conf` (we should think more about the path name, but for prototyping and hooking up the app's internal logic correctly, this is fine), exists, the app will read it on boot.  That file can specify things like the two options suggested above:
* The default server (which the app would advance to on first startup).
* Whether the user is allowed to add other servers.

---------------------

And then for OSX/Windows, the work will be mostly figuring out how to replace "read a file" with the appropriate configuration management system(s) we want to support for the platform.

**Comment by ygini** [comment]
I'm not familiar with Windows side either, but for macOS (and iOS) I know it perfectly well.

On both platform you've NSUserDefault class who's here to look for user's preferences relates to the app (you can use it to save your own user based preferences and load the defaults one).

When managed settings are pushed by the MDM, their are accessible the via this class.

On macOS, the keys you will set are directly available at the root of the dictionary.

On iOS, it's available via a sub dictionary accessible via the key `com.apple.configuration.managed`.

Tell me if you need advices for the iOS/macOS part (I'm sorry but I'm way too busy to actually implement it).

**Comment by akashnimare** [comment]
@ygini are there any desktop apps which have this kinda support?

**Comment by ygini** [comment]
@akashnimare all apps that comply with macOS developer guideline are manageable by default (just using NSUserDefault to store your settings make your app manageable).

And most important apps like Microsoft Office offer dedicated management options nowadays (like AutoFill and AutoAdvance for SAML based authentication).

**Comment by ghost** [comment]
I'm currently looking for a way to do this on linux (with windows as a lower priority). Is there any (even hacky) way to accomplish even the default organization right now?

**Comment by abhigyank** [comment]
@swallitsch A hacky way could be to add the org in config file already and distribute.
In `~/.config/Zulip/config/domain.json` , a default first organization can be manually added in this way - 
```
{
    "domains": [
        {
            "icon": "/home/<username>/.config/Zulip/server-icons/1662569173.png",
            "url": "https://chat.zulip.org",
            "alias": "Zulip Community"
        },
    ]
}
```

**Comment by akashnimare** [comment]
@swallitsch, @ygini we just added this feature in https://github.com/zulip/zulip-desktop/pull/681. Docs [here](https://github.com/zulip/zulip-desktop/blob/master/docs/Enterprise.md). Please test it and let us know if you have any feedbacks etc.

**Comment by ygini** [comment]
Hello

The implementation for macOS is bad, as said on my original post it must be MCX Based (so you must read NSUserDefaults on your specific domain of preferences). 

This is the only way to provide management feature on macOS. 

Your file based implementation will not be used because not compatible with MDM, and MDM is what everyone use for macOS management.

Your current solution does not answer my initial request (where I was already saying that MCX is mandatory for macOS and GPO for Windows).

Stick to my initial recommendation if you want your solution to be used.

**Comment by priyank-p** [comment]
@ygini Hello there!

The reason we did not provide the MCX based enterprise support for macos, and Windows Group Policy for windows is because we can't access those on our side. [electron](https://electronjs.org), the framework we use to build our desktop app doesn't provide such ability as of now.

The next step if you want to see this thing moving will be to [file a issue upstream to electron](https://github.com/electron/electron/issues/new/choose) to provide a API for MCX and Windows Group Policy. I will be glad to file a issue upstream if you provide more details on how exactly the MCX based enterprise management works. Is it where a administrator provides config in `.plist` file?

**Comment by ygini** [comment]
Administrators with MCX and MDM will provide values readable only via NSUserDefaults API, you can't try to directly read anything on the system because it's composed of multiple different plist.

And it's already supported by Electron for what I see in the documentation: https://github.com/electron/electron/blob/master/docs/api/system-preferences.md#systempreferencesgetuserdefaultkey-type-macos

Simply use `systemPreferences.getUserDefault(key, type)` when you are on macOS host and it should work.

**Comment by priyank-p** [comment]
Given that electron supports it, can you give us details on how one would set values to `NSUserDefaults` API (this is the steps one needs to do in macos to set the values up), that will help us to effectively document it and test it one the feature is ready.

**Comment by ygini** [comment]
Here is a sample profile

Save it as `zulip.mobileconfig` and open it on macOS, it will set for you the keys in NSUserDefaults.

This kind of profile can be installed manually for testing purpose or deployed via MDM. Behavior for you are the same.

```<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
    <dict>
        <key>PayloadIdentifier</key>
        <string>org.zulip.zulip-electron.customsettings</string>
        <key>PayloadRemovalDisallowed</key>
        <false />
        <key>PayloadScope</key>
        <string>User</string>
        <key>PayloadType</key>
        <string>Configuration</string>
        <key>PayloadUUID</key>
        <string>02387e20-3a50-0134-d705-0050568eda4e</string>
        <key>PayloadOrganization</key>
        <string>Zulip</string>
        <key>PayloadVersion</key>
        <integer>1</integer>
        <key>PayloadDisplayName</key>
        <string>Zulip Managed Settings</string>
        <key>PayloadContent</key>
        <array>
            <dict>
                <key>PayloadType</key>
                <string>com.apple.ManagedClient.preferences</string>
                <key>PayloadVersion</key>
                <integer>1</integer>
                <key>PayloadIdentifier</key>
                <string>org.zulip.zulip-electron.customsettings.1efeaf00-3a50-0134-d706-0050568eda4e</string>
                <key>PayloadUUID</key>
                <string>1efeaf00-3a50-0134-d706-0050568eda4e</string>
                <key>PayloadEnabled</key>
                <true />
                <key>PayloadDisplayName</key>
                <string>Zulip Managed Settings</string>
                <key>PayloadContent</key>
                <dict>
                    <key>org.zulip.zulip-electron</key>
                    <dict>
                        <key>Forced</key>
                        <array>
                            <dict>
                                <key>mcx_preference_settings</key>
                                <dict>
                                    <key>presetOrganizations</key>
                                    <array>
                                    	<string>https://chat.zulip.org</string>
                                    </array>
                                    <key>autoUpdate</key>
                                    <false />
                                </dict>
                            </dict>
                        </array>
                    </dict>
                </dict>
            </dict>
        </array>
    </dict>
</plist>```

**Comment by ygini** [comment]
Also, the same exist for iOS (look at Mattermost doc here https://docs.mattermost.com/mobile/mobile-appconfig.html) but this one will require that you own a MDM to test it. 

The main difference between iOS and macOS is here: with macOS the IT directly manage your preference domain so simply reading NSUserDefault will do the job.

On iOS, all managed keys are stored in a specific dictionary accessible via NSUserDefault under the key `com.apple.configuration.managed`.

Aside of that, the idea is the same.
