### ISSUE TITLE
Report issue modal has vestigial scrollbars.

### ISSUE THREAD

**Issue by rishig** [zulip/zulip-desktop#569]
A minor issue, but the scrollbar arrows on the right and bottom sides don't do anything on click:

![image](https://user-images.githubusercontent.com/890911/46029825-500f8300-c0a9-11e8-8986-121b2e05a8cc.png)

**Comment by akashnimare** [comment]
@priyankp10 does this require changes in your feedback module?

**Comment by priyank-p** [comment]
AFAICT, this is an browser artifact. I think this should be/is only an issue on windows and linux. The arrows should be disabled and they are since they are faded out in the picture since there is nowhere to scroll. In windows and linux they should up even when they are not needed.

I think instead of `overflow: scroll;` which should be used, if we can change it to `overflow: auto` this could be fixed so they scrollbar will not appear unless needed and when they do they will be usable.

(I will put up a experimental PR for this in a bit, if it works I will fix it upstream, and release a new version).
