### ISSUE TITLE
Organization Avatar not changing

### ISSUE THREAD

**Issue by Mentalone** [zulip/zulip-desktop#680]
We are unable to change the Organization Logo.  It stays with either the Z or an H while in the App.  

With console up, I do get this every time that I try to upload:

![image](https://user-images.githubusercontent.com/48458920/54164005-9e7ac900-4420-11e9-8285-47a42f8ff12d.png)

**Comment by abhigyank** [comment]
My understanding of why you see a Z or h icon is because of self signed certificates. In case you choose to ignore certificate warnings and proceed in an insecure manner we do not fetch server icon. To fix that you can add the certificate in Settings-> Organization. 
Not sure if this is the reason for TypeError.

**Comment by timabbott** [comment]
@abhigyank hmm, is this something we can change?  If the user decides to ignore the cert warning, we should presumably let them proceed with using that server fully...

**Comment by timabbott** [comment]
(In any case, the TypeError looks like a definite bug in any case)

**Comment by abhigyank** [comment]
> @abhigyank hmm, is this something we can change? If the user decides to ignore the cert warning, we should presumably let them proceed with using that server fully...

Created #684

**Comment by abhigyank** [comment]
> (In any case, the TypeError looks like a definite bug in any case)

Okay, I figured the `TypeError` cause - There is no server icon display on the left sidebar (due to any issue) and we are using the fallback - show first character of the realm name - and the user updates the server icon in the realm, this causes `electron-bridge` to try and update the server icon on the left sidebar but since it is not there we get this error of undefined of `serverImgs[index].src` . 

>  If the user decides to ignore the cert warning, we should presumably let them proceed with using that server fully...

Should be fixed in #685 .

**Comment by vsvipul** [comment]
@Mentalone can you test now by pulling master? It should be fixed now.

**Comment by Mentalone** [comment]
@vsvipul Good for us, we setup the certificate so we now show the logo.  The bad for the sake of testing, is that we can't test this now. Sorry.

We can now see our logo show up after adding the cert.  Thank you for all your help!

**Comment by abhigyank** [comment]
To solve the TypeError part one will have to create a new element with the new logo in the sidebar.

**Comment by vsvipul** [comment]
I think this can be closed now. (was a certs problem) . Fixed in #685.
