### ISSUE TITLE
UI is not so good as Slack — font is too small by default

### ISSUE THREAD

**Issue by develar** [zulip/zulip-desktop#786]
---

- **Operating System**:
  - [ ] Windows
  - [ ] Linux/Ubuntu
  - [* ] macOS
- **Clear steps to reproduce the issue**:
- **Relevant error messages and/or screenshots**:

I am not really happy that electron-builder migrated from slack to zulip because of zulip UI.
In short, UI looks a little bit outdated and not modern. Not so attractive.

To be more specific,

1. I find font too small and not crisp, compared not only to Slack, but to Github and any apps.
2. I think that for main messages white background should be used, and for sidebars grayed background (Slack, IDEA, Finder and other apps).

<img width="1904" alt="Screenshot 2019-07-04 at 21 10 31" src="https://user-images.githubusercontent.com/350686/60684829-2ee18b80-9ea0-11e9-945a-e81f45763a33.png">

Do you see difference? A huge difference — in Slack font is a bigger and more crisp.

**Comment by akashnimare** [comment]
Hey :)

I didn't know that electron-builder moved to Zulip. Great news. 

> I find font too small and not crisp, compared not only to Slack, but to Github and any apps.

We are aware of the issue and I think we do have some open PRs which fixes this. @rishig would have more idea about this. We have made a lot of changes in the UI recently. Would be very helpful if you can post your feedback/suggestions etc [here](https://chat.zulip.org/#narrow/stream/101-design).

**Comment by vsvipul** [comment]
@develar Also, regarding the font size, you can Zoom In on the app (Ctrl+=) as a temporary fix, while this is discussed and improved upon.

**Comment by timabbott** [comment]
We do have plans to increase the default font size of Zulip, first as an option and then as the default.  Zoom is a pretty good workaround in the meantime.

**Comment by vsvipul** [comment]
@develar Also, in the desktop app, you can inject custom CSS, so that the look gets changed. For example, a user made a custom CSS file [here](https://chat.zulip.org/#narrow/stream/101-design/topic/ideas.20for.20a.20new.20theme/near/738589), which you can try out. Looks great and you can also change it according to your requirements, meanwhile. Thanks for this @schrej .

**Comment by develar** [comment]
@vsvipul Yes, it looks much better than default (because sidebar is gray and you can focus on content). I find content blocks a little bit aggressive (too more blocks, slack approach is better suited, because opposite to Github, chat platform messages in most cases are not so long, and so, no need to use so many separators — it only adds visual noise).

Great, that on this front there is some progress :)

(screenshot from non-Apple retina Dell monitor 24")

<img width="1125" alt="Screen Shot 2019-07-10 at 16 37 10" src="https://user-images.githubusercontent.com/350686/60978192-0f7bb000-a331-11e9-8027-d0c84046de43.png">

**Comment by adityamudgil2505** [comment]
@akashnimare @timabbott @vsvipul  Can we provide a feature of some **predefine CSS theme** (as shown in the gif) so that the user can choose his favourite one and along with custom CSS theme which he/she can upload. 
And currently, custom CSS theme is not stored inside the application, somehow if the user deletes some files which by mistake includes custom css theme which he/she uses in the desktop application, now the user will not able to use that theme. Therefore, the 
**CSS theme should be store inside the application** as it doesn't take many sizes of the application.

GIF
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25535045/76944449-0662ca00-6927-11ea-8247-29a4462036c9.gif)

**Comment by akashnimare** [comment]
We can add this if it adds value.

**Comment by adityamudgil2505** [comment]
@akashnimare It will be easy for the user to customize there UI without adding a CSS script.

**Comment by vchuravy** [comment]
More and easier UI customization would be good! Especially font-size and selecting between a less and more dense layout as well as selecting color-scheme. I find Zulip a lot more tiring for my eyes.

**Comment by akashnimare** [comment]
@timabbott do you think we should add this as an experiment? It doesn't hurt to add a few predefined themes.

**Comment by timabbott** [comment]
I don't think there's a coherent way for us to add maintainable CSS themes from inside the desktop app codebase.  We have a "night theme" feature in the webapp, and it requires 700 lines of CSS despite significant effort towards refactoring things to limit how much CSS is needed there.  And we need to change that CSS often in a fashion that's atomic with design changes in the webapp for it to not be broken, which wouldn't be possible with a feature in the desktop app codebase.

We do have plans to add support for different densities in the webapp, but that isn't an issue for the desktop project.  And I imagine in the future we may add support for additional themes in the web UI codebase as well in addition to the "night" theme.  But I don't think it makes sense to build more of a themes feature in the desktop app codebase.
