### ISSUE TITLE
Try not button doesn't reconnect to network

### ISSUE THREAD

**Issue by CodeDoctorDE** [zulip/zulip-desktop#798]
The offline screen does not disappear when I have wifi.
- **Operating System**:
  - [ ] Windows
  - [x] Linux/Ubuntu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
Disconnect with the wifi and reconnect.

**Comment by akashnimare** [comment]
@CodeDoctorDE it should auto-reload the app. Can you attach a gif/video of the issue?

**Comment by CodeDoctorDE** [comment]
The reload button in the left bottom corner works perfect. 
But the screen does not appear. You must click on the organisation to go away from this. But the screen is there in the sidebar!

**Comment by akashnimare** [comment]
Would be really helpful if you can attach a gif/video of the issue.

**Comment by CodeDoctorDE** [comment]
My pc is private, sorry.
You can reproduce this error with disconnect with the wifi

**Comment by muskankhedia** [comment]
@akashnimare, I was looking for this issue, and I came up with the same bug. The gif below describes the complete working:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/36980003/64075659-9d906900-ccd8-11e9-804c-729b2d95ef7c.gif)

**Comment by muskankhedia** [comment]
@akashnimare, I think [PR #723](https://github.com/zulip/zulip-desktop/pull/723) solves in problem somehow. Further, Can I work on this issue?

**Comment by akashnimare** [comment]
@muskankhedia I think #819 might fix this. Can you reproduce the issue on master?

**Comment by muskankhedia** [comment]
@akashnimare The gif I had mentioned before is produced in the master branch code of the repository itself and it still exists. The problem I have figured out is on connecting to the internet connection, the page is getting auto-reload, but as the active page is no-network page, it is reloading that page instead of navigating to any other organization page.

**Comment by akashnimare** [comment]
@muskankhedia can you please check back again on master?

**Comment by akashnimare** [comment]
> The problem I have figured out is on connecting to the internet connection, the page is getting auto-reload, but as the active page is no-network page, it is reloading that page instead of navigating to any other organization page.

Okay, okay got it. I think this used to work as expected, don't know what's wrong. @kanishk98 might have something on this. @muskankhedia feel free to look into this. #723 could fix this.

**Comment by muskankhedia** [comment]
@akashnimare yaa sure... I tried it again in master branch and the bug is reproduced the same way as earlier.

**Comment by kanishk98** [comment]
> @kanishk98 might have something on this.

Thanks for the mention! I think this is a problem with the `is-online` package (#819 just fixes the Try Now button). I'd started work on #723 because another user had a similar issue, so we'd chosen to remove `is-online` module entirely and just rely on a simple request for the server's favicon. Regardless, I think #723 does solve this (at least it does on my end). It'll be great if others can test it out too. 

It also includes a check for a server getting invalidated after it is added, so we can test out that feature too. 🚀

**Comment by akashnimare** [comment]
@muskankhedia can you test if #723 fixes this issue?

**Comment by muskankhedia** [comment]
@akashnimare, Yes, I tested the pull request in my system(presently using fedora 30) and it solves the issue [#798](https://github.com/zulip/zulip-desktop/issues/798). Now the Zulip server reconnects after getting online and also the new tab displaying the message "Network Error" gets deleted.

**Comment by akashnimare** [comment]
Awesome, thanks.

**Comment by akashnimare** [comment]
Closing since it's fixed.
