### ISSUE TITLE
The app should check whether it's actually loading Zulip

### ISSUE THREAD

**Issue by zingmars** [zulip/zulip-desktop#813]
- **Operating System**:
  - [x] Windows
  - [ ] Linux/Ubuntu
  - [ ] macOS 

Easier for me to just show you:
![image](https://user-images.githubusercontent.com/917126/63675140-cd2f0500-c7f0-11e9-9f26-674832a8bc52.png)

Basically what happened here was that Riot got pushed to the URL that once held a Zulip instance. Now instead of giving an error that it's not connected to Zulip, the Zulip app is running Riot instead. 

A similar issue ocurrs when you right click an image in Zulip and press View Image, which opens the image, forcing you to look for the back button.

The funny part? Riot works just fine. I've yet to run into any issues.

**Comment by akashnimare** [comment]
@zingmars ahh, that is a bummer. BTW, is that Zulip instance public so that I can test it? What version are you on? We recently pushed [v4.0.0](https://github.com/zulip/zulip-desktop/releases) where we have updated our validation logic for a Zulip server and I'm hoping it should cover your case as well.

**Comment by zingmars** [comment]
That Zulip instance is behind a firewall now, sorry. It should be trivial to test it by setting up a Zulip instance, connecting to it using the client then making the web server serve literally any other app to that address.

Version is Zulip v4.0.0. To be fair, as a user all I need to do is to remove this server and connect to the new URL, but it's quite funny seeing it like this. I'm going to keep the Zulip app with Riot instance up on this computer to see if future updates fix this and if and when it breaks the Zulip app.

**Comment by akashnimare** [comment]
Cool, removing and readding the server should fix this issue. @kanishk98, @vsvipul are we validating/checking already added servers on app load?

**Comment by kanishk98** [comment]
> are we validating/checking already added servers on app load?

Yeah, we call `updateSavedServer()`, which calls `checkDomain()` - the problem is we only have a `then` block, not a `catch` block. So even though our server validation logic would detect that Riot isn't a real Zulip server, the app doesn't know what to do with that info. 

I'll just send in a PR to fix that. Thanks for pointing this out, @zingmars!

**Comment by moeenio** [comment]
The funniest with this is that you can browse literally any page modifying the `domains.json` file.
And notifications will work.

**Comment by akashnimare** [comment]
I'll go ahead and close this since we have already fixed this issue. 

> The funniest with this is that you can browse literally any page modifying the domains.json file. And notifications will work

This won't work in the latest master. I'll push a new release soon so that you can test the same :)
