### ISSUE TITLE
Notification system integration

### ISSUE THREAD

**Issue by lastmikoi** [zulip/zulip-desktop#9]
Under Linux, Zulip notifications are displayed through a notification bubble from the systray icon.

It would be interesting to make Zulip send notifications to an available `notification-daemon` through D-BUS (see https://people.gnome.org/~mccann/docs/notification-spec/notification-spec-latest.html#commands), so that notifications would be integrated into already-existing notification systems (such as popular Desktop Environments or standalone daemons such as dunst)

Using the `libnotify` library might be a way to achieve that behaviour.

**Comment by lfaraone** [comment]
Thanks @lastmikoi ! 

The place to implement this would be [`PlatformInterface.cpp`](https://github.com/zulip/zulip-desktop/blob/master/src/PlatformInterface.cpp#L82); that file is used on Linux environments and currently just does:

```
    APP->mainWindow()->trayIcon()->showMessage(title, content);
```

**Comment by excieve** [comment]
I'm not experienced with C++ or Qt but I'd like to give it a try if no one else is working on it.

Utilising `libnotify` is probably undesirable as it brings in several Gtk-world dependencies. The options I can think of is either using Qt's D-Bus classes directly or use `qdbusxml2cpp` utility to generate a proxy class from the XML interface definition and use that.

I've never used either approach so unless there's strong opinion over one of them, I'd try to generate a proxy and see the result. If it's satisfactory — go forward with it, otherwise manually call the interface via Qt's D-Bus machinery. This shouldn't be too bad either as notifications interface isn't that complex, especially given we only need a small subset of it.

**Comment by excieve** [comment]
Right, so the generated proxy code looks sane to me but a little bit different for Qt4 and Qt5. Fortunately this can be handled by cmake macros at build time. So unless there are any objections I'll just go on and implement it this way.
