### ISSUE TITLE
The SUID sandbox helper binary was found

### ISSUE THREAD

**Issue by fauust** [zulip/zulip-desktop#912]
---

- **Operating System**:
  - [ ] Windows
  - [x] Linux/Ubuntu
  - [ ] macOS

OS: Debian Buster
Window Manager: i3wm + polybar

- **Clear steps to reproduce the issue**:

Upgrade from 4.0.3 to 5.0:

```bash
sudo apt upgrade
```

- **Relevant error messages and/or screenshots**:

Start zulip from the terminal:

```bash
❯ zulip
[3240919:0401/102546.414325:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Zulip/chrome-sandbox is owned by root and has mode 4755.`
```

Resolved by:
```bash
sudo chmod 4755 /opt/Zulip/chrome-sandbox
```

**Comment by andersk** [comment]
Indeed, it seems our custom `afterInstall` script overrides the `electron-builder` default, which would otherwise run `chmod 4755 '/opt/Zulip/chrome-sandbox' || true`.

This isn’t a problem on Ubuntu kernels, which enable unprivileged `CLONE_NEWUSER`, avoiding the need for the setuid sandbox. But Debian kernels carry a custom patch to disable unprivileged `CLONE_NEWUSER` by default; it can be reenabled with `sysctl kernel.unprivileged_userns_clone=1`.

We’ll fix the `afterInstall` script in the next release.

**Comment by fauust** [comment]
Thanks @andersk!
